coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true

ignore:
  - "dist/**"
  - "scripts/**"
  - "**/*.test.ts"

